# Generated by Django 3.1.4 on 2020-12-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condole', '0002_message_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='death',
            name='age',
        ),
        migrations.AddField(
            model_name='death',
            name='birth_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='death',
            name='death_year',
            field=models.IntegerField(null=True),
        ),
    ]
