# Generated by Django 3.1.4 on 2020-12-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condole', '0003_auto_20201230_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='death',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
